# Generated by Django 5.1.1 on 2024-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('table', models.TextField(blank=True, null=True)),
                ('chart', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
